export interface TimeZone {
    id: number;
    displayName: string;
}

export const timezones: TimeZone[] = [
    { id: 2, displayName: '(GMT) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London' },
    { id: 3, displayName: '(GMT+01:00) Brussels, Copenhagen, Madrid, Paris' },
    { id: 4, displayName: '(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna' },
    { id: 5, displayName: '(GMT+02:00) Athens, Bucharest, Istanbul' },
    { id: 6, displayName: '(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague' },
    { id: 7, displayName: '(GMT+02:00) Minsk' },
    { id: 8, displayName: '(GMT-03:00) Brasilia' },
    { id: 9, displayName: '(GMT-04:00) Atlantic Time (Canada)' },
    { id: 10, displayName: '(GMT-05:00) Eastern Time (US and Canada)' },
    { id: 11, displayName: '(GMT-06:00) Central Time (US and Canada)' },
    { id: 12, displayName: '(GMT-07:00) Mountain Time (US and Canada)' },
    { id: 13, displayName: '(GMT-08:00) Pacific Time (US and Canada)' },
    { id: 14, displayName: '(GMT-09:00) Alaska' },
    { id: 15, displayName: '(GMT-10:00) Hawaii' },
    { id: 16, displayName: '(GMT-11:00) Midway Island, Samoa' },
    { id: 17, displayName: '(GMT+12:00) Auckland, Wellington' },
    { id: 18, displayName: '(GMT+10:00) Brisbane' },
    { id: 19, displayName: '(GMT+09:30) Adelaide' },
    { id: 20, displayName: '(GMT+09:00) Osaka, Sapporo, Tokyo' },
    { id: 21, displayName: '(GMT+08:00) Kuala Lumpur, Singapore' },
    { id: 22, displayName: '(GMT+07:00) Bangkok, Hanoi, Jakarta' },
    { id: 23, displayName: '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi' },
    { id: 24, displayName: '(GMT+04:00) Abu Dhabi, Muscat' },
    { id: 25, displayName: '(GMT+03:30) Tehran' },
    { id: 26, displayName: '(GMT+03:00) Baghdad' },
    { id: 27, displayName: '(GMT+02:00) Jerusalem' },
    { id: 28, displayName: '(GMT-03:30) Newfoundland' },
    { id: 29, displayName: '(GMT-01:00) Azores' },
    { id: 30, displayName: '(GMT-02:00) Mid-Atlantic' },
    { id: 31, displayName: '(GMT) Casablanca, Monrovia, Reykjavik' },
    { id: 32, displayName: '(GMT-03:00) Buenos Aires, Georgetown' },
    { id: 33, displayName: '(GMT-04:00) Caracas, La Paz' },
    { id: 34, displayName: '(GMT-05:00) Indiana (East)' },
    { id: 35, displayName: '(GMT-05:00) Bogota, Lima, Quito, Rio Branco' },
    { id: 36, displayName: '(GMT-06:00) Saskatchewan' },
    { id: 37, displayName: '(GMT-06:00) Guadalajara, Mexico City, Monterrey' },
    { id: 38, displayName: '(GMT-07:00) Arizona' },
    { id: 39, displayName: '(GMT-12:00) International Date Line West' },
    { id: 40, displayName: '(GMT+12:00) Fiji Is., Kamchatka, Marshall Is.' },
    { id: 41, displayName: '(GMT+11:00) Magadan, Solomon Is., New Caledonia' },
    { id: 42, displayName: '(GMT+10:00) Hobart' },
    { id: 43, displayName: '(GMT+10:00) Guam, Port Moresby' },
    { id: 44, displayName: '(GMT+09:30) Darwin' },
    { id: 45, displayName: '(GMT+08:00) Beijing, Chongqing, Hong Kong S.A.R., Urumqi' },
    { id: 46, displayName: '(GMT+06:00) Almaty, Novosibirsk' },
    { id: 47, displayName: '(GMT+05:00) Islamabad, Karachi, Tashkent' },
    { id: 48, displayName: '(GMT+04:30) Kabul' },
    { id: 49, displayName: '(GMT+02:00) Cairo' },
    { id: 50, displayName: '(GMT+02:00) Harare, Pretoria' },
    { id: 51, displayName: '(GMT+03:00) Moscow, St. Petersburg, Volgograd' },
    { id: 53, displayName: '(GMT-01:00) Cape Verde Is.' },
    { id: 54, displayName: '(GMT+04:00) Baku' },
    { id: 55, displayName: '(GMT-06:00) Central America' },
    { id: 56, displayName: '(GMT+03:00) Nairobi' },
    { id: 57, displayName: '(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb' },
    { id: 58, displayName: '(GMT+05:00) Ekaterinburg' },
    { id: 59, displayName: '(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius' },
    { id: 60, displayName: '(GMT-03:00) Greenland' },
    { id: 61, displayName: '(GMT+06:30) Yangon (Rangoon)' },
    { id: 62, displayName: '(GMT+05:45) Kathmandu' },
    { id: 63, displayName: '(GMT+08:00) Irkutsk, Ulaan Bataar' },
    { id: 64, displayName: '(GMT+07:00) Krasnoyarsk' },
    { id: 65, displayName: '(GMT-04:00) Santiago' },
    { id: 66, displayName: '(GMT+05:30) Sri Jayawardenepura' },
    { id: 67, displayName: '(GMT+13:00) Nuku\'alofa' },
    { id: 68, displayName: '(GMT+10:00) Vladivostok' },
    { id: 69, displayName: '(GMT+01:00) West Central Africa' },
    { id: 70, displayName: '(GMT+09:00) Yakutsk' },
    { id: 71, displayName: '(GMT+06:00) Astana, Dhaka' },
    { id: 72, displayName: '(GMT+09:00) Seoul' },
    { id: 73, displayName: '(GMT+08:00) Perth' },
    { id: 74, displayName: '(GMT+03:00) Kuwait, Riyadh' },
    { id: 75, displayName: '(GMT+08:00) Taipei' },
    { id: 76, displayName: '(GMT+10:00) Canberra, Melbourne, Sydney' },
    { id: 77, displayName: '(GMT-07:00) Chihuahua, La Paz, Mazatlan' },
    { id: 78, displayName: '(GMT-08:00) Tijuana, Baja California' },
    { id: 79, displayName: '(GMT+02:00) Amman' },
    { id: 80, displayName: '(GMT+02:00) Beirut' },
    { id: 81, displayName: '(GMT-04:00) Manaus' },
    { id: 82, displayName: '(GMT+03:00) Tbilisi' },
    { id: 83, displayName: '(GMT+02:00) Windhoek' },
    { id: 84, displayName: '(GMT+04:00) Yerevan' }
];
