name: 🐞 Bug report
description: If something is not working as expected please open up a bug to help us fix the issue ASAP and improve the product.
title: "🐞 Bug report: "
labels: ["🐞 bug", "👀 needs peer review"]
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting the issue you are facing.
        
        Please complete the below form to ensure we have the necessary details to assist you.
  - type: dropdown
    id: bug-priority
    attributes:
      label: ⭐ Priority
      description: Let us know how this issue is affecting you
      options:
        - (Low)☹️ Something is a little off
        - (Medium)😢 I'm annoyed but I'll live
        - (Urgent)⚠️😱 I can't use the extension
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: 📝 Describe the bug
      description: Provide a clear description of the bug
    validations:
      required: true
  - type: textarea
    id: bug-repro-steps
    attributes:
      label: 👣 Steps To Reproduce
      description: Add steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    id: bug-expected-behavior
    attributes:
      label: 📜 Expected behavior
      description: Provide a clear description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: bug-image
    attributes:
      label: 📷 Screenshots
      description: If applicable, add screenshots to help explain your problem
    validations:
      required: false
  - type: input
    id: bug-spfx-toolkit-version
    attributes:
      label: ❓SharePoint Framework Toolkit version
      description: Provide the version of the SharePoint Framework Toolkit you are using
    validations:
      required: false
  - type: input
    id: bug-node-version
    attributes:
      label: ❓Node.js version
      description: |
        Provide the version of nodejs you are using
        
        Execute `node -v` in your terminal to identify your version
    validations:
      required: false 
  - type: textarea
    id: bug-more-info
    attributes:
      label: 🤔 Additional context
      description: Add any other context or information about the problem here
    validations:
      required: false
