name: Check Tests

on: 
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'pnp'
    name: "Test"
    runs-on: windows-latest
    timeout-minutes: 40

    permissions:
      contents: read

    steps:
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      
      - name: Checkout SPFx Toolkit
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          path: vscode-viva
        
      - name: Install dependencies for SPFx Toolkit
        run: npm ci --ignore-scripts --omit=optional
        working-directory: vscode-viva
        env:
          npm_config_omit: optional

      - name: Build SPFx Toolkit
        run: npm run package
        working-directory: vscode-viva

      - name: Compile tests for SPFx Toolkit
        run: npm run compile-tests
        working-directory: vscode-viva

      - name: Run tests for SPFx Toolkit
        run: npm run test
        working-directory: vscode-viva
      
