name: Check Tests

on: 
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'pnp'
    name: "Test"
    runs-on: windows-latest
    timeout-minutes: 40

    permissions:
      contents: read

    steps:
      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      
      - name: Checkout SPFx Toolkit
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          path: vscode-viva
        
      - name: Install dependencies for SPFx Toolkit
        run: npm ci --ignore-scripts --omit=optional
        working-directory: vscode-viva

      - name: Build SPFx Toolkit
        run: npm run package
        working-directory: vscode-viva

      - name: Compile tests for SPFx Toolkit
        run: npm run compile-tests
        working-directory: vscode-viva

      - name: Run tests for SPFx Toolkit
        run: npm run test
        working-directory: vscode-viva
      
