name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'pnp'
    name: "Build and release"
    runs-on: ubuntu-latest
    timeout-minutes: 40

    permissions:
      contents: write
      packages: read

    steps:
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      
      - name: Checkout vscode-viva
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          path: vscode-viva
        
      - name: Install the dependencies
        run: npm ci --ignore-scripts --omit=optional
        working-directory: vscode-viva

      - name: Install vsce
        run: npm install --global --ignore-scripts @vscode/vsce@3.3.2
        working-directory: vscode-viva

      - name: Publish
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
        working-directory: vscode-viva